spring.application.name=Ending
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.initialization-fail-timeout= 60000
spring.datasource.hikari.connection-timeout= 60000
server.port= 8082
spring.profiles.active = test
